//This file is used for setting random numbers (0-14) to variables 'EDAGAME[A-O]ANI'.
//These numbers are mutually different and used in the Task System of 'Animals' game, where they represent task audios.

var EDAGAMEAANI;
function EDAGAMENumAANI() {
	
	EDAGAMEAANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEAANI);
	document.getElementById('EDAGAMENumber').innerHTML = EDAGAMEAANI;
	EDAGAMENumBANI();
	
};

var EDAGAMEBANI;
function EDAGAMENumBANI() {
	
	EDAGAMEBANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEBANI);
	if (EDAGAMEBANI == EDAGAMEAANI) {EDAGAMENumBANI();}
	else {EDAGAMENumCANI();};
	
};

var EDAGAMECANI;
function EDAGAMENumCANI() {
	
	EDAGAMECANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMECANI);
	if ((EDAGAMECANI == EDAGAMEAANI) || 
		(EDAGAMECANI == EDAGAMEBANI)) {EDAGAMENumCANI();}
	else {EDAGAMENumDANI();};
	
};

var EDAGAMEDANI;
function EDAGAMENumDANI() {
	
	EDAGAMEDANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEDANI);
	if ((EDAGAMEDANI == EDAGAMEAANI) ||
		(EDAGAMEDANI == EDAGAMEBANI) ||
		(EDAGAMEDANI == EDAGAMECANI)) {EDAGAMENumDANI();}
	else {EDAGAMENumEANI();};
	
};

var EDAGAMEEANI;
function EDAGAMENumEANI() {
	
	EDAGAMEEANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEEANI);
	if ((EDAGAMEEANI == EDAGAMEAANI) || 
		(EDAGAMEEANI == EDAGAMEBANI) || 
		(EDAGAMEEANI == EDAGAMECANI) || 
		(EDAGAMEEANI == EDAGAMEDANI)) {EDAGAMENumEANI();}
	else {EDAGAMENumFANI();};
	
};

var EDAGAMEFANI;
function EDAGAMENumFANI() {
	
	EDAGAMEFANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEFANI);
	if ((EDAGAMEFANI == EDAGAMEAANI) ||
		(EDAGAMEFANI == EDAGAMEBANI) ||
		(EDAGAMEFANI == EDAGAMECANI) ||
		(EDAGAMEFANI == EDAGAMEDANI) ||
		(EDAGAMEFANI == EDAGAMEEANI)) {EDAGAMENumFANI();}
	else {EDAGAMENumGANI();};

};

var EDAGAMEGANI;
function EDAGAMENumGANI() {
	
	EDAGAMEGANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEGANI);
	if ((EDAGAMEGANI == EDAGAMEAANI) ||
		(EDAGAMEGANI == EDAGAMEBANI) ||
		(EDAGAMEGANI == EDAGAMECANI) ||
		(EDAGAMEGANI == EDAGAMEDANI) ||
		(EDAGAMEGANI == EDAGAMEEANI) ||
		(EDAGAMEGANI == EDAGAMEFANI)) {EDAGAMENumGANI();}
	else {EDAGAMENumHANI();};
	
};

var EDAGAMEHANI;
function EDAGAMENumHANI() {
	
	EDAGAMEHANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEHANI);
	if ((EDAGAMEHANI == EDAGAMEAANI) ||
		(EDAGAMEHANI == EDAGAMEBANI) ||
		(EDAGAMEHANI == EDAGAMECANI) ||
		(EDAGAMEHANI == EDAGAMEDANI) ||
		(EDAGAMEHANI == EDAGAMEEANI) ||
		(EDAGAMEHANI == EDAGAMEFANI) ||
		(EDAGAMEHANI == EDAGAMEGANI)) {EDAGAMENumHANI();}
	else {EDAGAMENumIANI();};
	
};

var EDAGAMEIANI;
function EDAGAMENumIANI() {
	
	EDAGAMEIANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEIANI);
	if ((EDAGAMEIANI == EDAGAMEAANI) ||
		(EDAGAMEIANI == EDAGAMEBANI) ||
		(EDAGAMEIANI == EDAGAMECANI) ||
		(EDAGAMEIANI == EDAGAMEDANI) ||
		(EDAGAMEIANI == EDAGAMEEANI) ||
		(EDAGAMEIANI == EDAGAMEFANI) ||
		(EDAGAMEIANI == EDAGAMEGANI) ||
		(EDAGAMEIANI == EDAGAMEHANI)) {EDAGAMENumIANI();}
	else {EDAGAMENumJANI();};
	
};

var EDAGAMEJANI;
function EDAGAMENumJANI() {
	
	EDAGAMEJANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEJANI);
	if ((EDAGAMEJANI == EDAGAMEAANI) ||
		(EDAGAMEJANI == EDAGAMEBANI) ||
		(EDAGAMEJANI == EDAGAMECANI) ||
		(EDAGAMEJANI == EDAGAMEDANI) ||
		(EDAGAMEJANI == EDAGAMEEANI) ||
		(EDAGAMEJANI == EDAGAMEFANI) ||
		(EDAGAMEJANI == EDAGAMEGANI) ||
		(EDAGAMEJANI == EDAGAMEHANI) ||
		(EDAGAMEJANI == EDAGAMEIANI)) {EDAGAMENumJANI();}
	else {EDAGAMENumKANI();};
	
};

var EDAGAMEKANI;
function EDAGAMENumKANI() {
	
	EDAGAMEKANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEKANI);
	if ((EDAGAMEKANI == EDAGAMEAANI) ||
		(EDAGAMEKANI == EDAGAMEBANI) ||
		(EDAGAMEKANI == EDAGAMECANI) ||
		(EDAGAMEKANI == EDAGAMEDANI) ||
		(EDAGAMEKANI == EDAGAMEEANI) ||
		(EDAGAMEKANI == EDAGAMEFANI) ||
		(EDAGAMEKANI == EDAGAMEGANI) ||
		(EDAGAMEKANI == EDAGAMEHANI) ||
		(EDAGAMEKANI == EDAGAMEIANI) ||
		(EDAGAMEKANI == EDAGAMEJANI)) {EDAGAMENumKANI();}
	else {EDAGAMENumLANI();};
	
};

var EDAGAMELANI;
function EDAGAMENumLANI() {
	
	EDAGAMELANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMELANI);
	if ((EDAGAMELANI == EDAGAMEAANI) ||
		(EDAGAMELANI == EDAGAMEBANI) ||
		(EDAGAMELANI == EDAGAMECANI) ||
		(EDAGAMELANI == EDAGAMEDANI) ||
		(EDAGAMELANI == EDAGAMEEANI) ||
		(EDAGAMELANI == EDAGAMEFANI) ||
		(EDAGAMELANI == EDAGAMEGANI) ||
		(EDAGAMELANI == EDAGAMEHANI) ||
		(EDAGAMELANI == EDAGAMEIANI) ||
		(EDAGAMELANI == EDAGAMEJANI) ||
		(EDAGAMELANI == EDAGAMEKANI)) {EDAGAMENumLANI();}
	else {EDAGAMENumMANI();};
	
};

var EDAGAMEMANI;
function EDAGAMENumMANI() {
	
	EDAGAMEMANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEMANI);
	if ((EDAGAMEMANI == EDAGAMEAANI) ||
		(EDAGAMEMANI == EDAGAMEBANI) ||
		(EDAGAMEMANI == EDAGAMECANI) ||
		(EDAGAMEMANI == EDAGAMEDANI) ||
		(EDAGAMEMANI == EDAGAMEEANI) ||
		(EDAGAMEMANI == EDAGAMEFANI) ||
		(EDAGAMEMANI == EDAGAMEGANI) ||
		(EDAGAMEMANI == EDAGAMEHANI) ||
		(EDAGAMEMANI == EDAGAMEIANI) ||
		(EDAGAMEMANI == EDAGAMEJANI) ||
		(EDAGAMEMANI == EDAGAMEKANI) ||
		(EDAGAMEMANI == EDAGAMELANI)) {EDAGAMENumMANI();}
	else {EDAGAMENumNANI();};
	
};

var EDAGAMENANI;
function EDAGAMENumNANI() {
	
	EDAGAMENANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMENANI);
	if ((EDAGAMENANI == EDAGAMEAANI) ||
		(EDAGAMENANI == EDAGAMEBANI) ||
		(EDAGAMENANI == EDAGAMECANI) ||
		(EDAGAMENANI == EDAGAMEDANI) ||
		(EDAGAMENANI == EDAGAMEEANI) ||
		(EDAGAMENANI == EDAGAMEFANI) ||
		(EDAGAMENANI == EDAGAMEGANI) ||
		(EDAGAMENANI == EDAGAMEHANI) ||
		(EDAGAMENANI == EDAGAMEIANI) ||
		(EDAGAMENANI == EDAGAMEJANI) ||
		(EDAGAMENANI == EDAGAMEKANI) ||
		(EDAGAMENANI == EDAGAMELANI) ||
		(EDAGAMENANI == EDAGAMEMANI)) {EDAGAMENumNANI();}
	else {EDAGAMENumOANI();};
	
};

var EDAGAMEOANI;
function EDAGAMENumOANI() {
	
	EDAGAMEOANI = Math.floor(Math.random() * EDAGAMEVoicesAnimalsTask.length); Number(EDAGAMEOANI); 
	if ((EDAGAMEOANI == EDAGAMEAANI) ||
		(EDAGAMEOANI == EDAGAMEBANI) ||
		(EDAGAMEOANI == EDAGAMECANI) ||
		(EDAGAMEOANI == EDAGAMEDANI) ||
		(EDAGAMEOANI == EDAGAMEEANI) ||
		(EDAGAMEOANI == EDAGAMEFANI) ||
		(EDAGAMEOANI == EDAGAMEGANI) ||
		(EDAGAMEOANI == EDAGAMEHANI) ||
		(EDAGAMEOANI == EDAGAMEIANI) ||
		(EDAGAMEOANI == EDAGAMEJANI) ||
		(EDAGAMEOANI == EDAGAMEKANI) ||
		(EDAGAMEOANI == EDAGAMELANI) ||
		(EDAGAMEOANI == EDAGAMEMANI) ||
		(EDAGAMEOANI == EDAGAMENANI)) {EDAGAMENumOANI();};
		
};