//This file is used for setting random numbers (0-19) to variables 'EDAGAME[A-T]SHA'.
//These numbers are mutually different and used in the Task System of 'Shapes' game, where they represent task audios.

var EDAGAMEASHA;
function EDAGAMENumASHA() {
	
	EDAGAMEASHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEASHA);
	document.getElementById('EDAGAMENumber').innerHTML = EDAGAMEASHA;
	EDAGAMENumBSHA();
	
};

var EDAGAMEBSHA;
function EDAGAMENumBSHA() {
	
	EDAGAMEBSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEBSHA);
	if (EDAGAMEBSHA == EDAGAMEASHA) {EDAGAMENumBSHA();}
	else {EDAGAMENumCSHA();};
	
};

var EDAGAMECSHA;
function EDAGAMENumCSHA() {
	
	EDAGAMECSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMECSHA);
	if ((EDAGAMECSHA == EDAGAMEASHA) || 
		(EDAGAMECSHA == EDAGAMEBSHA)) {EDAGAMENumCSHA();}
	else {EDAGAMENumDSHA();};
		
};

var EDAGAMEDSHA;
function EDAGAMENumDSHA() {
	
	EDAGAMEDSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEDSHA);
	if ((EDAGAMEDSHA == EDAGAMEASHA) ||
		(EDAGAMEDSHA == EDAGAMEBSHA) ||
		(EDAGAMEDSHA == EDAGAMECSHA)) {EDAGAMENumDSHA();}
	else {EDAGAMENumESHA();};
	
};

var EDAGAMEESHA;
function EDAGAMENumESHA() {
	
	EDAGAMEESHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEESHA);
	if ((EDAGAMEESHA == EDAGAMEASHA) || 
		(EDAGAMEESHA == EDAGAMEBSHA) || 
		(EDAGAMEESHA == EDAGAMECSHA) || 
		(EDAGAMEESHA == EDAGAMEDSHA)) {EDAGAMENumESHA();}
	else {EDAGAMENumFSHA();};
		
};

var EDAGAMEFSHA;
function EDAGAMENumFSHA() {
	
	EDAGAMEFSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEFSHA);
	if ((EDAGAMEFSHA == EDAGAMEASHA) ||
		(EDAGAMEFSHA == EDAGAMEBSHA) ||
		(EDAGAMEFSHA == EDAGAMECSHA) ||
		(EDAGAMEFSHA == EDAGAMEDSHA) ||
		(EDAGAMEFSHA == EDAGAMEESHA)) {EDAGAMENumFSHA();}
	else {EDAGAMENumGSHA();};
	
};

var EDAGAMEGSHA;
function EDAGAMENumGSHA() {
	
	EDAGAMEGSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEGSHA);
	if ((EDAGAMEGSHA == EDAGAMEASHA) ||
		(EDAGAMEGSHA == EDAGAMEBSHA) ||
		(EDAGAMEGSHA == EDAGAMECSHA) ||
		(EDAGAMEGSHA == EDAGAMEDSHA) ||
		(EDAGAMEGSHA == EDAGAMEESHA) ||
		(EDAGAMEGSHA == EDAGAMEFSHA)) {EDAGAMENumGSHA();}
	else {EDAGAMENumHSHA();};
	
};

var EDAGAMEHSHA;
function EDAGAMENumHSHA() {
	
	EDAGAMEHSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEHSHA);
	if ((EDAGAMEHSHA == EDAGAMEASHA) ||
		(EDAGAMEHSHA == EDAGAMEBSHA) ||
		(EDAGAMEHSHA == EDAGAMECSHA) ||
		(EDAGAMEHSHA == EDAGAMEDSHA) ||
		(EDAGAMEHSHA == EDAGAMEESHA) ||
		(EDAGAMEHSHA == EDAGAMEFSHA) ||
		(EDAGAMEHSHA == EDAGAMEGSHA)) {EDAGAMENumHSHA();}
	else {EDAGAMENumISHA();};
	
};

var EDAGAMEISHA;
function EDAGAMENumISHA() {
	
	EDAGAMEISHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEISHA);
	if ((EDAGAMEISHA == EDAGAMEASHA) ||
		(EDAGAMEISHA == EDAGAMEBSHA) ||
		(EDAGAMEISHA == EDAGAMECSHA) ||
		(EDAGAMEISHA == EDAGAMEDSHA) ||
		(EDAGAMEISHA == EDAGAMEESHA) ||
		(EDAGAMEISHA == EDAGAMEFSHA) ||
		(EDAGAMEISHA == EDAGAMEGSHA) ||
		(EDAGAMEISHA == EDAGAMEHSHA)) {EDAGAMENumISHA();}	
	else {EDAGAMENumJSHA();};
	
};

var EDAGAMEJSHA;
function EDAGAMENumJSHA() {
	
	EDAGAMEJSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEJSHA);
	if ((EDAGAMEJSHA == EDAGAMEASHA) ||
		(EDAGAMEJSHA == EDAGAMEBSHA) ||
		(EDAGAMEJSHA == EDAGAMECSHA) ||
		(EDAGAMEJSHA == EDAGAMEDSHA) ||
		(EDAGAMEJSHA == EDAGAMEESHA) ||
		(EDAGAMEJSHA == EDAGAMEFSHA) ||
		(EDAGAMEJSHA == EDAGAMEGSHA) ||
		(EDAGAMEJSHA == EDAGAMEHSHA) ||
		(EDAGAMEJSHA == EDAGAMEISHA)) {EDAGAMENumJSHA();}
	else {EDAGAMENumKSHA();};
	
};

var EDAGAMEKSHA;
function EDAGAMENumKSHA() {
	
	EDAGAMEKSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEKSHA);
	if ((EDAGAMEKSHA == EDAGAMEASHA) ||
		(EDAGAMEKSHA == EDAGAMEBSHA) ||
		(EDAGAMEKSHA == EDAGAMECSHA) ||
		(EDAGAMEKSHA == EDAGAMEDSHA) ||
		(EDAGAMEKSHA == EDAGAMEESHA) ||
		(EDAGAMEKSHA == EDAGAMEFSHA) ||
		(EDAGAMEKSHA == EDAGAMEGSHA) ||
		(EDAGAMEKSHA == EDAGAMEHSHA) ||
		(EDAGAMEKSHA == EDAGAMEISHA) ||
		(EDAGAMEKSHA == EDAGAMEJSHA)) {EDAGAMENumKSHA();}
	else {EDAGAMENumLSHA();};
	
};

var EDAGAMELSHA;
function EDAGAMENumLSHA() {
	
	EDAGAMELSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMELSHA);
	if ((EDAGAMELSHA == EDAGAMEASHA) ||
		(EDAGAMELSHA == EDAGAMEBSHA) ||
		(EDAGAMELSHA == EDAGAMECSHA) ||
		(EDAGAMELSHA == EDAGAMEDSHA) ||
		(EDAGAMELSHA == EDAGAMEESHA) ||
		(EDAGAMELSHA == EDAGAMEFSHA) ||
		(EDAGAMELSHA == EDAGAMEGSHA) ||
		(EDAGAMELSHA == EDAGAMEHSHA) ||
		(EDAGAMELSHA == EDAGAMEISHA) ||
		(EDAGAMELSHA == EDAGAMEJSHA) ||
		(EDAGAMELSHA == EDAGAMEKSHA)) {EDAGAMENumLSHA();}
	else {EDAGAMENumMSHA();};
	
};

var EDAGAMEMSHA;
function EDAGAMENumMSHA() {
	
	EDAGAMEMSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEMSHA);
	if ((EDAGAMEMSHA == EDAGAMEASHA) ||
		(EDAGAMEMSHA == EDAGAMEBSHA) ||
		(EDAGAMEMSHA == EDAGAMECSHA) ||
		(EDAGAMEMSHA == EDAGAMEDSHA) ||
		(EDAGAMEMSHA == EDAGAMEESHA) ||
		(EDAGAMEMSHA == EDAGAMEFSHA) ||
		(EDAGAMEMSHA == EDAGAMEGSHA) ||
		(EDAGAMEMSHA == EDAGAMEHSHA) ||
		(EDAGAMEMSHA == EDAGAMEISHA) ||
		(EDAGAMEMSHA == EDAGAMEJSHA) ||
		(EDAGAMEMSHA == EDAGAMEKSHA) ||
		(EDAGAMEMSHA == EDAGAMELSHA)) {EDAGAMENumMSHA();}
	else {EDAGAMENumNSHA();};
	
};

var EDAGAMENSHA;
function EDAGAMENumNSHA() {
	
	EDAGAMENSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMENSHA);
	if ((EDAGAMENSHA == EDAGAMEASHA) ||
		(EDAGAMENSHA == EDAGAMEBSHA) ||
		(EDAGAMENSHA == EDAGAMECSHA) ||
		(EDAGAMENSHA == EDAGAMEDSHA) ||
		(EDAGAMENSHA == EDAGAMEESHA) ||
		(EDAGAMENSHA == EDAGAMEFSHA) ||
		(EDAGAMENSHA == EDAGAMEGSHA) ||
		(EDAGAMENSHA == EDAGAMEHSHA) ||
		(EDAGAMENSHA == EDAGAMEISHA) ||
		(EDAGAMENSHA == EDAGAMEJSHA) ||
		(EDAGAMENSHA == EDAGAMEKSHA) ||
		(EDAGAMENSHA == EDAGAMELSHA) ||
		(EDAGAMENSHA == EDAGAMEMSHA)) {EDAGAMENumNSHA();}
	else {EDAGAMENumOSHA();};
	
};

var EDAGAMEOSHA;
function EDAGAMENumOSHA() {
	
	EDAGAMEOSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEOSHA); 
	if ((EDAGAMEOSHA == EDAGAMEASHA) ||
		(EDAGAMEOSHA == EDAGAMEBSHA) ||
		(EDAGAMEOSHA == EDAGAMECSHA) ||
		(EDAGAMEOSHA == EDAGAMEDSHA) ||
		(EDAGAMEOSHA == EDAGAMEESHA) ||
		(EDAGAMEOSHA == EDAGAMEFSHA) ||
		(EDAGAMEOSHA == EDAGAMEGSHA) ||
		(EDAGAMEOSHA == EDAGAMEHSHA) ||
		(EDAGAMEOSHA == EDAGAMEISHA) ||
		(EDAGAMEOSHA == EDAGAMEJSHA) ||
		(EDAGAMEOSHA == EDAGAMEKSHA) ||
		(EDAGAMEOSHA == EDAGAMELSHA) ||
		(EDAGAMEOSHA == EDAGAMEMSHA) ||
		(EDAGAMEOSHA == EDAGAMENSHA)) {EDAGAMENumOSHA();}		
	else {EDAGAMENumPSHA();};
	
};
							  
var EDAGAMEPSHA;
function EDAGAMENumPSHA() {
	
	EDAGAMEPSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEPSHA); 
	if ((EDAGAMEPSHA == EDAGAMEASHA) ||
		(EDAGAMEPSHA == EDAGAMEBSHA) ||
		(EDAGAMEPSHA == EDAGAMECSHA) ||
		(EDAGAMEPSHA == EDAGAMEDSHA) ||
		(EDAGAMEPSHA == EDAGAMEESHA) ||
		(EDAGAMEPSHA == EDAGAMEFSHA) ||
		(EDAGAMEPSHA == EDAGAMEGSHA) ||
		(EDAGAMEPSHA == EDAGAMEHSHA) ||
		(EDAGAMEPSHA == EDAGAMEISHA) ||
		(EDAGAMEPSHA == EDAGAMEJSHA) ||
		(EDAGAMEPSHA == EDAGAMEKSHA) ||
		(EDAGAMEPSHA == EDAGAMELSHA) ||
		(EDAGAMEPSHA == EDAGAMEMSHA) ||
		(EDAGAMEPSHA == EDAGAMENSHA) ||
		(EDAGAMEPSHA == EDAGAMEOSHA)) {EDAGAMENumPSHA();}
	else {EDAGAMENumQSHA();};
	
};
							  
var EDAGAMEQSHA;
function EDAGAMENumQSHA() {
	
	EDAGAMEQSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMEQSHA); 
	if ((EDAGAMEQSHA == EDAGAMEASHA) ||
		(EDAGAMEQSHA == EDAGAMEBSHA) ||
		(EDAGAMEQSHA == EDAGAMECSHA) ||
		(EDAGAMEQSHA == EDAGAMEDSHA) ||
		(EDAGAMEQSHA == EDAGAMEESHA) ||
		(EDAGAMEQSHA == EDAGAMEFSHA) ||
		(EDAGAMEQSHA == EDAGAMEGSHA) ||
		(EDAGAMEQSHA == EDAGAMEHSHA) ||
		(EDAGAMEQSHA == EDAGAMEISHA) ||
		(EDAGAMEQSHA == EDAGAMEJSHA) ||
		(EDAGAMEQSHA == EDAGAMEKSHA) ||
		(EDAGAMEQSHA == EDAGAMELSHA) ||
		(EDAGAMEQSHA == EDAGAMEMSHA) ||
		(EDAGAMEQSHA == EDAGAMENSHA) ||
		(EDAGAMEQSHA == EDAGAMEOSHA) ||
		(EDAGAMEQSHA == EDAGAMEPSHA)) {EDAGAMENumQSHA();}
	else {EDAGAMENumRSHA();};
	
};
							  
var EDAGAMERSHA;
function EDAGAMENumRSHA() {
	
	EDAGAMERSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMERSHA); 
	if ((EDAGAMERSHA == EDAGAMEASHA) ||
		(EDAGAMERSHA == EDAGAMEBSHA) ||
		(EDAGAMERSHA == EDAGAMECSHA) ||
		(EDAGAMERSHA == EDAGAMEDSHA) ||
		(EDAGAMERSHA == EDAGAMEESHA) ||
		(EDAGAMERSHA == EDAGAMEFSHA) ||
		(EDAGAMERSHA == EDAGAMEGSHA) ||
		(EDAGAMERSHA == EDAGAMEHSHA) ||
		(EDAGAMERSHA == EDAGAMEISHA) ||
		(EDAGAMERSHA == EDAGAMEJSHA) ||
		(EDAGAMERSHA == EDAGAMEKSHA) ||
		(EDAGAMERSHA == EDAGAMELSHA) ||
		(EDAGAMERSHA == EDAGAMEMSHA) ||
		(EDAGAMERSHA == EDAGAMENSHA) ||
		(EDAGAMERSHA == EDAGAMEOSHA) ||
		(EDAGAMERSHA == EDAGAMEPSHA) ||
		(EDAGAMERSHA == EDAGAMEQSHA)) {EDAGAMENumRSHA();}
	else {EDAGAMENumSSHA();};
	
};
							  
var EDAGAMESSHA;
function EDAGAMENumSSHA() {
	
	EDAGAMESSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMESSHA); 
	if ((EDAGAMESSHA == EDAGAMEASHA) ||
		(EDAGAMESSHA == EDAGAMEBSHA) ||
		(EDAGAMESSHA == EDAGAMECSHA) ||
		(EDAGAMESSHA == EDAGAMEDSHA) ||
		(EDAGAMESSHA == EDAGAMEESHA) ||
		(EDAGAMESSHA == EDAGAMEFSHA) ||
		(EDAGAMESSHA == EDAGAMEGSHA) ||
		(EDAGAMESSHA == EDAGAMEHSHA) ||
		(EDAGAMESSHA == EDAGAMEISHA) ||
		(EDAGAMESSHA == EDAGAMEJSHA) ||
		(EDAGAMESSHA == EDAGAMEKSHA) ||
		(EDAGAMESSHA == EDAGAMELSHA) ||
		(EDAGAMESSHA == EDAGAMEMSHA) ||
		(EDAGAMESSHA == EDAGAMENSHA) ||
		(EDAGAMESSHA == EDAGAMEOSHA) ||
		(EDAGAMESSHA == EDAGAMEPSHA) ||
		(EDAGAMESSHA == EDAGAMEQSHA) ||
		(EDAGAMESSHA == EDAGAMERSHA)) {EDAGAMENumSSHA();}
	else {EDAGAMENumTSHA();};
	
};
							  
var EDAGAMETSHA;
function EDAGAMENumTSHA() {
	
	EDAGAMETSHA = Math.floor(Math.random() * EDAGAMEVoicesShapesTask.length); Number(EDAGAMETSHA); 
	if ((EDAGAMETSHA == EDAGAMEASHA) ||
		(EDAGAMETSHA == EDAGAMEBSHA) ||
		(EDAGAMETSHA == EDAGAMECSHA) ||
		(EDAGAMETSHA == EDAGAMEDSHA) ||
		(EDAGAMETSHA == EDAGAMEESHA) ||
		(EDAGAMETSHA == EDAGAMEFSHA) ||
		(EDAGAMETSHA == EDAGAMEGSHA) ||
		(EDAGAMETSHA == EDAGAMEHSHA) ||
		(EDAGAMETSHA == EDAGAMEISHA) ||
		(EDAGAMETSHA == EDAGAMEJSHA) ||
		(EDAGAMETSHA == EDAGAMEKSHA) ||
		(EDAGAMETSHA == EDAGAMELSHA) ||
		(EDAGAMETSHA == EDAGAMEMSHA) ||
		(EDAGAMETSHA == EDAGAMENSHA) ||
		(EDAGAMETSHA == EDAGAMEOSHA) ||
		(EDAGAMETSHA == EDAGAMEPSHA) ||
		(EDAGAMETSHA == EDAGAMEQSHA) ||
		(EDAGAMETSHA == EDAGAMERSHA) ||
		(EDAGAMETSHA == EDAGAMESSHA)) {EDAGAMENumTSHA();};
		
};